version: "3.4"

x-docker-data: &docker-file-info
  build:
    context: .
    dockerfile: Dockerfile

services:
  web:
    <<: *docker-file-info
    depends_on:
      - postgres
    ports:
      - 80:8000
    command: server
  test:
    <<: *docker-file-info
    depends_on:
      - postgres
    command: python manage.py test
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:12.2-alpine
