# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('日', models.CharField(max_length=40)),
                ('一', models.CharField(max_length=40)),
                ('二', models.CharField(max_length=40)),
                ('三', models.CharField(max_length=40)),
                ('四', models.CharField(max_length=40)),
                ('五', models.CharField(max_length=40)),
                ('六', models.CharField(max_length=40)),
                ('類型', models.CharField(max_length=40)),
                ('米其林星', models.CharField(max_length=40)),
                ('停車', models.CharField(max_length=40)),
                ('外送', models.CharField(max_length=40)),
                ('先繳訂金', models.CharField(max_length=40)),
                ('評價', models.FloatField(max_length=40)),
                ('地理位子', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
