# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200307_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='一',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='三',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='二',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='五',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='六',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='四',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='日',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='一end',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='一start',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='三end',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='三start',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='二end',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='二start',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='五end',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='五start',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='六end',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='六start',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='四end',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='四start',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='日end',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='日start',
            field=models.CharField(default='', max_length=30),
        ),
    ]
