# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-03-07 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200307_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='一end',
            new_name='fri_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='一start',
            new_name='fri_start',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='三end',
            new_name='mon_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='三start',
            new_name='mon_start',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='二end',
            new_name='satur_send',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='二start',
            new_name='satur_start',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='五end',
            new_name='sun_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='五start',
            new_name='sun_start',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='六end',
            new_name='thur_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='六start',
            new_name='thur_start',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='四end',
            new_name='tue_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='四start',
            new_name='tue_start',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='日end',
            new_name='wed_end',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='日start',
            new_name='wed_start',
        ),
    ]
