from django.db import models


class Restaurant(models.Model):
    name = models.CharField(max_length=30)
    sun_start = models.CharField(max_length=30, default='')
    mon_start = models.CharField(max_length=30, default='')
    tue_start = models.CharField(max_length=30, default='')
    wed_start = models.CharField(max_length=30, default='')
    thur_start = models.CharField(max_length=30, default='')
    fri_start = models.CharField(max_length=30, default='')
    satur_start = models.CharField(max_length=30, default='')
    sun_end = models.CharField(max_length=30, default='')
    mon_end = models.CharField(max_length=30, default='')
    tue_end = models.CharField(max_length=30, default='')
    wed_end = models.CharField(max_length=30, default='')
    thur_end = models.CharField(max_length=30, default='')
    fri_end = models.CharField(max_length=30, default='')
    satur_send = models.CharField(max_length=30, default='')
    類型 = models.CharField(max_length=40)
    米其林星 = models.CharField(max_length=40)
    停車 = models.CharField(max_length=40)
    外送 = models.CharField(max_length=40)
    先繳訂金 = models.CharField(max_length=40)
    評價 = models.FloatField(max_length=40)
    地理位子 = models.CharField(max_length=40)